import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import TopLeftImg from "@/components/TopLeftImg";
import Transition from "@/components/Transition";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nik | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sora  bg-bg text-white">
        <TopLeftImg />
        <Image
          src={"/portfolio/home-bg.jpg"}
          alt="Home bg"
          width={1920}
          height={1080}
          className="absolute left-0 -z-10 bottom-0 opacity-25"
        />
        <Header />

        <Transition>{children}</Transition>

        <Navbar />
      </body>
    </html>
  );
}
